### ISSUE TITLE
menu-sidebar: add sidebar layout, update request page

### ISSUE THREAD

**Issue by pulakazad** [AlexisDrch/Ask#12]

**Comment by alexanderfache6** [comment]
Side bar is active but not switching to other pages. Theme of main activity is no longer visible.

**Comment by alexanderfache6** [comment]
Side bar can switch to other pages. Adding page information. Needs to fix issue with covering with main layout.

**Comment by alexanderfache6** [comment]
Fix calendar issue by changing order of fragments. Currently they are  flipped. Create first fragment wait for user to end current fragment, then create second fragment.
